'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with $1$ and $2$, the first $10$ terms will be:
$$1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

def p2(nn):
    sum = 0
    for n in range(nn):
        if n % 3 == 0 or n % 5 == 0:
            sum += n
    print(sum)

if __name__ == '__main__':
    p2(1000) # = 233168