'''
Even Fibonacci Numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

def p2(limit):
    term_1 = 0
    term_2 = 1

    next_term = 2
    even = 0
    liste = []
    
    while True:
        next_term = term_1 + term_2
        if next_term > limit:
            break
        if next_term % 2 == 0:
            even += next_term
            liste.append(next_term)
        term_1 = term_2
        term_2 = next_term

    print(even, liste)



if __name__ == '__main__':
    p2(4_000_000)