'''
Highly Divisible Triangle Number

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1+2+3+4+5+6+7 = 28.
The first ten terms would be 1,3,6,10,15,21,28,36,45,55...
Let us list the factors of the first seven triangle numbers:
                    1: 1
                    3: 1,3
                    6: 1,2,3,6
                    10: 1,2,5,10
                    15: 1,3,5,15
                    21: 1,3,7,21
                    28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?
'''

def p12():
    num = 0
    termAdder = 1

    while True:
        num += termAdder
        termAdder += 1
        divisors = findDivisors(num)

        if divisors > 500:
            print(num)
            break

def findDivisors(num):
    # With the help from https://stackoverflow.com/questions/110344/algorithm-to-calculate-the-number-of-divisors-of-a-given-number
    count = 2
    i = 2
    while i ** 2 < num:
        if num % i == 0:
             count += 2
        i += 1
    if i ** 2 == num:
         count += 1
    return count



if __name__ == '__main__':
        p12()